package presets

// platformPresets returns the 7 platform-specific presets.
func platformPresets() []Preset {
	return []Preset{
		{
			Key:          "discord",
			Name:         "Discord",
			Description:  "Fits within Discord's 10MB free-tier upload limit",
			Category:     CategoryPlatform,
			Codec:        "h264",
			Container:    "mp4",
			CRF:          23,
			Resolution:   "1280x720",
			AudioCodec:   "aac",
			AudioBitrate: "128k",
			SpeedPreset:  "medium",
			TargetSizeMB: 10,
			TwoPass:      true,
			Tags:         []string{"discord", "chat", "10mb", "free"},
			Icon:         "\U0001f3ae", // video game (Discord-ish)
		},
		{
			Key:          "discord-nitro",
			Name:         "Discord Nitro",
			Description:  "Fits within Discord Nitro's 50MB upload limit at 1080p",
			Category:     CategoryPlatform,
			Codec:        "h264",
			Container:    "mp4",
			CRF:          23,
			Resolution:   "1920x1080",
			AudioCodec:   "aac",
			AudioBitrate: "192k",
			SpeedPreset:  "medium",
			TargetSizeMB: 50,
			TwoPass:      true,
			Tags:         []string{"discord", "nitro", "50mb", "premium"},
			Icon:         "\U0001f680", // rocket
		},
		{
			Key:          "whatsapp",
			Name:         "WhatsApp",
			Description:  "Fits within WhatsApp's 16MB limit, capped at 30fps",
			Category:     CategoryPlatform,
			Codec:        "h264",
			Container:    "mp4",
			CRF:          23,
			Resolution:   "1280x720",
			MaxFPS:       30,
			AudioCodec:   "aac",
			AudioBitrate: "128k",
			SpeedPreset:  "medium",
			TargetSizeMB: 16,
			TwoPass:      true,
			Tags:         []string{"whatsapp", "mobile", "messaging", "16mb"},
			Icon:         "\U0001f4f1", // mobile phone
		},
		{
			Key:          "twitter",
			Name:         "Twitter / X",
			Description:  "Optimized for Twitter upload — 1080p max, 60fps, 140s recommended",
			Category:     CategoryPlatform,
			Codec:        "h264",
			Container:    "mp4",
			CRF:          23,
			Resolution:   "1920x1080",
			MaxFPS:       60,
			AudioCodec:   "aac",
			AudioBitrate: "192k",
			SpeedPreset:  "medium",
			Tags:         []string{"twitter", "x", "social", "140s"},
			Icon:         "\U0001f426", // bird
		},
		{
			Key:          "instagram",
			Name:         "Instagram",
			Description:  "Optimized for Instagram — 1080p max, 30fps, 60s recommended",
			Category:     CategoryPlatform,
			Codec:        "h264",
			Container:    "mp4",
			CRF:          23,
			Resolution:   "1920x1080",
			MaxFPS:       30,
			AudioCodec:   "aac",
			AudioBitrate: "128k",
			SpeedPreset:  "medium",
			Tags:         []string{"instagram", "ig", "social", "reels", "60s"},
			Icon:         "\U0001f4f7", // camera
		},
		{
			Key:          "tiktok",
			Name:         "TikTok",
			Description:  "Optimized for TikTok — 1080p max, 60fps, portrait-aware",
			Category:     CategoryPlatform,
			Codec:        "h264",
			Container:    "mp4",
			CRF:          23,
			Resolution:   "1920x1080",
			MaxFPS:       60,
			AudioCodec:   "aac",
			AudioBitrate: "128k",
			SpeedPreset:  "medium",
			Tags:         []string{"tiktok", "short", "vertical", "portrait", "social"},
			Icon:         "\U0001f3b5", // music note
		},
		{
			Key:          "youtube",
			Name:         "YouTube Upload",
			Description:  "Upload-optimized for YouTube — H.265, high quality, keeps resolution",
			Category:     CategoryPlatform,
			Codec:        "h265",
			Container:    "mp4",
			CRF:          18,
			AudioCodec:   "aac",
			AudioBitrate: "192k",
			SpeedPreset:  "medium",
			Tags:         []string{"youtube", "yt", "upload", "creator"},
			Icon:         "\u25b6\ufe0f", // play button
		},
	}
}
